name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | sh
          export PATH="$HOME/.pnpm/bin:$PATH"
          pnpm install

      - name: Build
        run: pnpm run build

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Zip and upload
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/${{ github.ref }}/win-unpacked
          asset_name: win-unpacked.zip
          asset_content_type: application/zip
          token: ${{ secrets.GH_TOKEN }}
