name: Test Publish

on: workflow_dispatch

jobs:
  get_github_token:
    runs-on: ubuntu-latest
    steps:
      - name: get token
        run: |
          echo ${{ secrets.GH_TOKEN }}

  publish_on_all_os:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 20
      - name: install dependencies
        run: npm install
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run publish
