name: Build Test 01

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Get latest tag
        id: get_latest_tag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_latest_tag.outputs.tag }}
          files: |
            ${{ github.workspace }}/release/dilidili.*
          token: ${{ secrets.GH_TOKEN }}
